"""
ECDAT Seed Signatures & Cryptographic Registry Definitions:
Populates the SQLite signature database with standardized cryptographic definitions
derived from NIST SP 800-131A/57, FIPS 203/204/205, BSI TR-02102, and Fraunhofer Crypistry.
"""

import sqlite3
from typing import List, Dict, Any

SEED_SIGNATURES: List[Dict[str, Any]] = [
    # ---------------------------------------------------------
    # GO ECOSYSTEM
    # ---------------------------------------------------------
    # Go cipher.Block
    {
        "id": "go.crypto.aes.newcipher",
        "ecosystem": "go",
        "namespace": "crypto/aes",
        "contract": "cipher.Block",
        "symbol": "NewCipher",
        "normalized_alg": "AES-256-GCM",
        "primitive_type": "ENCRYPTION",
        "key_size": 256,
        "classical_security_level": 256,
        "nist_quantum_security_level": 5,
        "default_risk": "LOW",
        "pqc_recommendation": "Maintain: AES-256 is quantum-safe under Grover's algorithm",
        "cwe": None,
        "description": "Go standard library AES block cipher constructor"
    },
    {
        "id": "go.crypto.des.newcipher",
        "ecosystem": "go",
        "namespace": "crypto/des",
        "contract": "cipher.Block",
        "symbol": "NewCipher",
        "normalized_alg": "DES",
        "primitive_type": "ENCRYPTION",
        "key_size": 64,
        "classical_security_level": 56,
        "nist_quantum_security_level": 0,
        "default_risk": "CRITICAL",
        "pqc_recommendation": "Migrate immediately: DES key length (56 bits) is broken against classical brute force",
        "cwe": "CWE-327",
        "description": "Go standard library DES block cipher constructor (Broken)"
    },
    {
        "id": "go.crypto.des.newtripledescipher",
        "ecosystem": "go",
        "namespace": "crypto/des",
        "contract": "cipher.Block",
        "symbol": "NewTripleDESCipher",
        "normalized_alg": "3DES",
        "primitive_type": "ENCRYPTION",
        "key_size": 192,
        "classical_security_level": 112,
        "nist_quantum_security_level": 0,
        "default_risk": "HIGH",
        "pqc_recommendation": "Migrate: 3DES is deprecated by NIST (Sweet32 vulnerability; migrate to AES-256)",
        "cwe": "CWE-327",
        "description": "Go standard library Triple-DES block cipher constructor (Deprecated)"
    },
    {
        "id": "go.crypto.rc4.newcipher",
        "ecosystem": "go",
        "namespace": "crypto/rc4",
        "contract": "cipher.Stream",
        "symbol": "NewCipher",
        "normalized_alg": "RC4",
        "primitive_type": "ENCRYPTION",
        "key_size": 128,
        "classical_security_level": 64,
        "nist_quantum_security_level": 0,
        "default_risk": "CRITICAL",
        "pqc_recommendation": "Migrate immediately: RC4 stream cipher biases make it broken",
        "cwe": "CWE-327",
        "description": "Go standard library RC4 stream cipher constructor (Broken)"
    },
    # Go cipher.AEAD
    {
        "id": "go.crypto.cipher.newgcm",
        "ecosystem": "go",
        "namespace": "crypto/cipher",
        "contract": "cipher.AEAD",
        "symbol": "NewGCM",
        "normalized_alg": "AES-GCM",
        "primitive_type": "ENCRYPTION",
        "key_size": 256,
        "classical_security_level": 256,
        "nist_quantum_security_level": 5,
        "default_risk": "LOW",
        "pqc_recommendation": "Maintain: AES-GCM provides standard authenticated encryption",
        "cwe": None,
        "description": "Go cipher.NewGCM Authenticated Encryption with Associated Data"
    },
    {
        "id": "go.xcrypto.chacha20poly1305.new",
        "ecosystem": "go",
        "namespace": "golang.org/x/crypto/chacha20poly1305",
        "contract": "cipher.AEAD",
        "symbol": "New",
        "normalized_alg": "ChaCha20-Poly1305",
        "primitive_type": "ENCRYPTION",
        "key_size": 256,
        "classical_security_level": 256,
        "nist_quantum_security_level": 5,
        "default_risk": "LOW",
        "pqc_recommendation": "Maintain: ChaCha20-Poly1305 is quantum-safe under Grover's algorithm",
        "cwe": None,
        "description": "Go x/crypto ChaCha20-Poly1305 AEAD constructor"
    },
    {
        "id": "go.xcrypto.chacha20poly1305.newx",
        "ecosystem": "go",
        "namespace": "golang.org/x/crypto/chacha20poly1305",
        "contract": "cipher.AEAD",
        "symbol": "NewX",
        "normalized_alg": "XChaCha20-Poly1305",
        "primitive_type": "ENCRYPTION",
        "key_size": 256,
        "classical_security_level": 256,
        "nist_quantum_security_level": 5,
        "default_risk": "LOW",
        "pqc_recommendation": "Maintain: XChaCha20-Poly1305 extended nonce AEAD",
        "cwe": None,
        "description": "Go x/crypto XChaCha20-Poly1305 extended nonce AEAD"
    },
    # Go hash.Hash
    {
        "id": "go.crypto.md5.new",
        "ecosystem": "go",
        "namespace": "crypto/md5",
        "contract": "hash.Hash",
        "symbol": "New",
        "normalized_alg": "MD5",
        "primitive_type": "HASH",
        "key_size": 128,
        "classical_security_level": 0,
        "nist_quantum_security_level": 0,
        "default_risk": "CRITICAL",
        "pqc_recommendation": "Migrate immediately: MD5 collisions broken; migrate to SHA-256/SHA-3",
        "cwe": "CWE-328",
        "description": "Go standard library MD5 digest constructor (Broken)"
    },
    {
        "id": "go.crypto.sha1.new",
        "ecosystem": "go",
        "namespace": "crypto/sha1",
        "contract": "hash.Hash",
        "symbol": "New",
        "normalized_alg": "SHA-1",
        "primitive_type": "HASH",
        "key_size": 160,
        "classical_security_level": 0,
        "nist_quantum_security_level": 0,
        "default_risk": "HIGH",
        "pqc_recommendation": "Migrate immediately: SHA-1 collision resistance is broken; migrate to SHA-256",
        "cwe": "CWE-328",
        "description": "Go standard library SHA-1 digest constructor (Broken)"
    },
    {
        "id": "go.crypto.sha256.new",
        "ecosystem": "go",
        "namespace": "crypto/sha256",
        "contract": "hash.Hash",
        "symbol": "New",
        "normalized_alg": "SHA-256",
        "primitive_type": "HASH",
        "key_size": 256,
        "classical_security_level": 256,
        "nist_quantum_security_level": 5,
        "default_risk": "LOW",
        "pqc_recommendation": "Maintain: SHA-256 is quantum-safe against collisions and preimage attacks",
        "cwe": None,
        "description": "Go standard library SHA-256 cryptographic digest"
    },
    {
        "id": "go.crypto.sha512.new",
        "ecosystem": "go",
        "namespace": "crypto/sha512",
        "contract": "hash.Hash",
        "symbol": "New",
        "normalized_alg": "SHA-512",
        "primitive_type": "HASH",
        "key_size": 512,
        "classical_security_level": 512,
        "nist_quantum_security_level": 5,
        "default_risk": "LOW",
        "pqc_recommendation": "Maintain: SHA-512 provides high security margin",
        "cwe": None,
        "description": "Go standard library SHA-512 cryptographic digest"
    },
    {
        "id": "go.crypto.hmac.new",
        "ecosystem": "go",
        "namespace": "crypto/hmac",
        "contract": "hash.Hash",
        "symbol": "New",
        "normalized_alg": "HMAC-SHA256",
        "primitive_type": "HASH",
        "key_size": 256,
        "classical_security_level": 256,
        "nist_quantum_security_level": 5,
        "default_risk": "LOW",
        "pqc_recommendation": "Maintain: HMAC provides keyed-hash message authentication",
        "cwe": None,
        "description": "Go standard library HMAC constructor"
    },
    # Go crypto.Signer / Asymmetric
    {
        "id": "go.crypto.rsa.generatekey",
        "ecosystem": "go",
        "namespace": "crypto/rsa",
        "contract": "crypto.Signer",
        "symbol": "GenerateKey",
        "normalized_alg": "RSA-2048",
        "primitive_type": "SIGNATURE",
        "key_size": 2048,
        "classical_security_level": 112,
        "nist_quantum_security_level": 0,
        "default_risk": "HIGH",
        "pqc_recommendation": "Migrate: RSA is vulnerable to Shor's algorithm (HNDL risk); migrate to ML-DSA or hybrid",
        "cwe": "CWE-326",
        "description": "Go crypto/rsa Key Generation"
    },
    {
        "id": "go.crypto.ecdsa.generatekey",
        "ecosystem": "go",
        "namespace": "crypto/ecdsa",
        "contract": "crypto.Signer",
        "symbol": "GenerateKey",
        "normalized_alg": "ECDSA-P256",
        "primitive_type": "SIGNATURE",
        "key_size": 256,
        "classical_security_level": 128,
        "nist_quantum_security_level": 0,
        "default_risk": "HIGH",
        "pqc_recommendation": "Migrate: Elliptic Curve signatures vulnerable to Shor's algorithm; migrate to ML-DSA-65",
        "cwe": "CWE-326",
        "description": "Go crypto/ecdsa Key Generation"
    },
    {
        "id": "go.crypto.ed25519.generatekey",
        "ecosystem": "go",
        "namespace": "crypto/ed25519",
        "contract": "crypto.Signer",
        "symbol": "GenerateKey",
        "normalized_alg": "Ed25519",
        "primitive_type": "SIGNATURE",
        "key_size": 256,
        "classical_security_level": 128,
        "nist_quantum_security_level": 0,
        "default_risk": "HIGH",
        "pqc_recommendation": "Migrate: Ed25519 vulnerable to Shor's algorithm; migrate to ML-DSA-65",
        "cwe": "CWE-326",
        "description": "Go crypto/ed25519 Key Generation"
    },
    # Go KDFs (golang.org/x/crypto/*)
    {
        "id": "go.xcrypto.argon2.idkey",
        "ecosystem": "go",
        "namespace": "golang.org/x/crypto/argon2",
        "contract": "KDF",
        "symbol": "IDKey",
        "normalized_alg": "Argon2id",
        "primitive_type": "KEY_EXCHANGE",
        "key_size": 256,
        "classical_security_level": 128,
        "nist_quantum_security_level": 5,
        "default_risk": "LOW",
        "pqc_recommendation": "Maintain: Argon2id is memory-hard and post-quantum robust",
        "cwe": None,
        "description": "Go x/crypto Argon2id password-based key derivation"
    },
    {
        "id": "go.xcrypto.bcrypt.generate",
        "ecosystem": "go",
        "namespace": "golang.org/x/crypto/bcrypt",
        "contract": "KDF",
        "symbol": "GenerateFromPassword",
        "normalized_alg": "Bcrypt",
        "primitive_type": "KEY_EXCHANGE",
        "key_size": 192,
        "classical_security_level": 128,
        "nist_quantum_security_level": 5,
        "default_risk": "LOW",
        "pqc_recommendation": "Maintain: Bcrypt adaptive password hashing",
        "cwe": None,
        "description": "Go x/crypto Bcrypt password hashing"
    },
    {
        "id": "go.xcrypto.scrypt.key",
        "ecosystem": "go",
        "namespace": "golang.org/x/crypto/scrypt",
        "contract": "KDF",
        "symbol": "Key",
        "normalized_alg": "Scrypt",
        "primitive_type": "KEY_EXCHANGE",
        "key_size": 256,
        "classical_security_level": 128,
        "nist_quantum_security_level": 5,
        "default_risk": "LOW",
        "pqc_recommendation": "Maintain: Scrypt memory-hard key derivation",
        "cwe": None,
        "description": "Go x/crypto Scrypt key derivation"
    },
    {
        "id": "go.xcrypto.pbkdf2.key",
        "ecosystem": "go",
        "namespace": "golang.org/x/crypto/pbkdf2",
        "contract": "KDF",
        "symbol": "Key",
        "normalized_alg": "PBKDF2",
        "primitive_type": "KEY_EXCHANGE",
        "key_size": 256,
        "classical_security_level": 128,
        "nist_quantum_security_level": 5,
        "default_risk": "MEDIUM",
        "pqc_recommendation": "Consider upgrade: PBKDF2 is CPU-bound; transition to Argon2id for password hashing",
        "cwe": None,
        "description": "Go x/crypto PBKDF2 key derivation"
    },
    {
        "id": "go.xcrypto.hkdf.new",
        "ecosystem": "go",
        "namespace": "golang.org/x/crypto/hkdf",
        "contract": "KDF",
        "symbol": "New",
        "normalized_alg": "HKDF",
        "primitive_type": "KEY_EXCHANGE",
        "key_size": 256,
        "classical_security_level": 256,
        "nist_quantum_security_level": 5,
        "default_risk": "LOW",
        "pqc_recommendation": "Maintain: HKDF HMAC-based Extract-and-Expand Key Derivation",
        "cwe": None,
        "description": "Go x/crypto HKDF key derivation"
    },
    # Go TLS & X509
    {
        "id": "go.crypto.tls.config",
        "ecosystem": "go",
        "namespace": "crypto/tls",
        "contract": "TLS",
        "symbol": "Config",
        "normalized_alg": "TLS-CONFIG",
        "primitive_type": "KEY_EXCHANGE",
        "key_size": None,
        "classical_security_level": 128,
        "nist_quantum_security_level": 0,
        "default_risk": "MEDIUM",
        "pqc_recommendation": "Enforce TLS 1.3 with post-quantum hybrid key exchange (X25519MLKEM768)",
        "cwe": None,
        "description": "Go crypto/tls Transport Layer Security Configuration"
    },
    {
        "id": "go.crypto.x509.parsecertificate",
        "ecosystem": "go",
        "namespace": "crypto/x509",
        "contract": "PKI",
        "symbol": "ParseCertificate",
        "normalized_alg": "X509-CERT",
        "primitive_type": "KEY_EXCHANGE",
        "key_size": None,
        "classical_security_level": 128,
        "nist_quantum_security_level": 0,
        "default_risk": "MEDIUM",
        "pqc_recommendation": "Audit certificate public keys for quantum migration (FIPS 204 ML-DSA)",
        "cwe": None,
        "description": "Go crypto/x509 X.509 Certificate Parser"
    },

    # ---------------------------------------------------------
    # JAVA ECOSYSTEM (JCA / JCE SPI)
    # ---------------------------------------------------------
    {
        "id": "java.jca.cipher.aes",
        "ecosystem": "java",
        "namespace": "javax.crypto.Cipher",
        "contract": "CipherSpi",
        "symbol": "getInstance",
        "normalized_alg": "AES",
        "primitive_type": "ENCRYPTION",
        "key_size": 256,
        "classical_security_level": 256,
        "nist_quantum_security_level": 5,
        "default_risk": "LOW",
        "pqc_recommendation": "Maintain: AES-256 is quantum-safe under Grover's algorithm",
        "cwe": None,
        "description": "Java JCA AES Cipher"
    },
    {
        "id": "java.jca.cipher.des",
        "ecosystem": "java",
        "namespace": "javax.crypto.Cipher",
        "contract": "CipherSpi",
        "symbol": "getInstance",
        "normalized_alg": "DES",
        "primitive_type": "ENCRYPTION",
        "key_size": 64,
        "classical_security_level": 56,
        "nist_quantum_security_level": 0,
        "default_risk": "CRITICAL",
        "pqc_recommendation": "Migrate immediately: DES (56-bit) is broken against brute force",
        "cwe": "CWE-327",
        "description": "Java JCA DES Cipher (Broken)"
    },
    {
        "id": "java.jca.cipher.3des",
        "ecosystem": "java",
        "namespace": "javax.crypto.Cipher",
        "contract": "CipherSpi",
        "symbol": "getInstance",
        "normalized_alg": "DESede",
        "primitive_type": "ENCRYPTION",
        "key_size": 192,
        "classical_security_level": 112,
        "nist_quantum_security_level": 0,
        "default_risk": "HIGH",
        "pqc_recommendation": "Migrate: 3DES is deprecated by NIST (Sweet32 vulnerability; migrate to AES-256)",
        "cwe": "CWE-327",
        "description": "Java JCA Triple-DES Cipher (Deprecated)"
    },
    {
        "id": "java.jca.cipher.blowfish",
        "ecosystem": "java",
        "namespace": "javax.crypto.Cipher",
        "contract": "CipherSpi",
        "symbol": "getInstance",
        "normalized_alg": "Blowfish",
        "primitive_type": "ENCRYPTION",
        "key_size": 128,
        "classical_security_level": 128,
        "nist_quantum_security_level": 0,
        "default_risk": "HIGH",
        "pqc_recommendation": "Migrate: Blowfish 64-bit block size vulnerable to birthday collisions (Sweet32)",
        "cwe": "CWE-327",
        "description": "Java JCA Blowfish Cipher"
    },
    {
        "id": "java.jca.cipher.rc4",
        "ecosystem": "java",
        "namespace": "javax.crypto.Cipher",
        "contract": "CipherSpi",
        "symbol": "getInstance",
        "normalized_alg": "RC4",
        "primitive_type": "ENCRYPTION",
        "key_size": 128,
        "classical_security_level": 64,
        "nist_quantum_security_level": 0,
        "default_risk": "CRITICAL",
        "pqc_recommendation": "Migrate immediately: RC4 stream cipher is broken",
        "cwe": "CWE-327",
        "description": "Java JCA RC4/ARCFOUR Cipher (Broken)"
    },
    {
        "id": "java.jca.digest.md5",
        "ecosystem": "java",
        "namespace": "java.security.MessageDigest",
        "contract": "MessageDigestSpi",
        "symbol": "getInstance",
        "normalized_alg": "MD5",
        "primitive_type": "HASH",
        "key_size": 128,
        "classical_security_level": 0,
        "nist_quantum_security_level": 0,
        "default_risk": "CRITICAL",
        "pqc_recommendation": "Migrate immediately: MD5 collision resistance is broken; migrate to SHA-256",
        "cwe": "CWE-328",
        "description": "Java JCA MD5 MessageDigest (Broken)"
    },
    {
        "id": "java.jca.digest.sha1",
        "ecosystem": "java",
        "namespace": "java.security.MessageDigest",
        "contract": "MessageDigestSpi",
        "symbol": "getInstance",
        "normalized_alg": "SHA-1",
        "primitive_type": "HASH",
        "key_size": 160,
        "classical_security_level": 0,
        "nist_quantum_security_level": 0,
        "default_risk": "HIGH",
        "pqc_recommendation": "Migrate immediately: SHA-1 collisions demonstrated; migrate to SHA-256",
        "cwe": "CWE-328",
        "description": "Java JCA SHA-1 MessageDigest (Broken)"
    },
    {
        "id": "java.jca.digest.sha256",
        "ecosystem": "java",
        "namespace": "java.security.MessageDigest",
        "contract": "MessageDigestSpi",
        "symbol": "getInstance",
        "normalized_alg": "SHA-256",
        "primitive_type": "HASH",
        "key_size": 256,
        "classical_security_level": 256,
        "nist_quantum_security_level": 5,
        "default_risk": "LOW",
        "pqc_recommendation": "Maintain: SHA-256 is quantum-safe",
        "cwe": None,
        "description": "Java JCA SHA-256 MessageDigest"
    },
    {
        "id": "java.jca.signature.rsa",
        "ecosystem": "java",
        "namespace": "java.security.Signature",
        "contract": "SignatureSpi",
        "symbol": "getInstance",
        "normalized_alg": "RSA-2048",
        "primitive_type": "SIGNATURE",
        "key_size": 2048,
        "classical_security_level": 112,
        "nist_quantum_security_level": 0,
        "default_risk": "HIGH",
        "pqc_recommendation": "Migrate: RSA signature vulnerable to Shor's algorithm; migrate to ML-DSA-65",
        "cwe": "CWE-326",
        "description": "Java JCA RSA Signature"
    },
    {
        "id": "java.jca.signature.ecdsa",
        "ecosystem": "java",
        "namespace": "java.security.Signature",
        "contract": "SignatureSpi",
        "symbol": "getInstance",
        "normalized_alg": "ECDSA-P256",
        "primitive_type": "SIGNATURE",
        "key_size": 256,
        "classical_security_level": 128,
        "nist_quantum_security_level": 0,
        "default_risk": "HIGH",
        "pqc_recommendation": "Migrate: ECDSA vulnerable to Shor's algorithm; migrate to ML-DSA-65",
        "cwe": "CWE-326",
        "description": "Java JCA ECDSA Signature"
    },
    {
        "id": "java.jca.ssl.context",
        "ecosystem": "java",
        "namespace": "javax.net.ssl.SSLContext",
        "contract": "SSLContextSpi",
        "symbol": "getInstance",
        "normalized_alg": "TLS-CONTEXT",
        "primitive_type": "KEY_EXCHANGE",
        "key_size": None,
        "classical_security_level": 128,
        "nist_quantum_security_level": 0,
        "default_risk": "MEDIUM",
        "pqc_recommendation": "Configure TLS 1.3 with post-quantum hybrid key exchange",
        "cwe": None,
        "description": "Java JSSE SSLContext"
    },

    # ---------------------------------------------------------
    # RUBY ECOSYSTEM (OpenSSL)
    # ---------------------------------------------------------
    {
        "id": "ruby.openssl.cipher.aes",
        "ecosystem": "ruby",
        "namespace": "OpenSSL::Cipher",
        "contract": "OpenSSL::Cipher",
        "symbol": "new",
        "normalized_alg": "AES-256-GCM",
        "primitive_type": "ENCRYPTION",
        "key_size": 256,
        "classical_security_level": 256,
        "nist_quantum_security_level": 5,
        "default_risk": "LOW",
        "pqc_recommendation": "Maintain: AES-256 is quantum-safe under Grover's algorithm",
        "cwe": None,
        "description": "Ruby OpenSSL AES-256-GCM Cipher"
    },
    {
        "id": "ruby.openssl.cipher.des",
        "ecosystem": "ruby",
        "namespace": "OpenSSL::Cipher",
        "contract": "OpenSSL::Cipher",
        "symbol": "new",
        "normalized_alg": "DES",
        "primitive_type": "ENCRYPTION",
        "key_size": 64,
        "classical_security_level": 56,
        "nist_quantum_security_level": 0,
        "default_risk": "CRITICAL",
        "pqc_recommendation": "Migrate immediately: DES (56-bit) is broken against brute force",
        "cwe": "CWE-327",
        "description": "Ruby OpenSSL DES Cipher (Broken)"
    },
    {
        "id": "ruby.openssl.digest.sha256",
        "ecosystem": "ruby",
        "namespace": "OpenSSL::Digest",
        "contract": "OpenSSL::Digest",
        "symbol": "new",
        "normalized_alg": "SHA-256",
        "primitive_type": "HASH",
        "key_size": 256,
        "classical_security_level": 256,
        "nist_quantum_security_level": 5,
        "default_risk": "LOW",
        "pqc_recommendation": "Maintain: SHA-256 is quantum-safe",
        "cwe": None,
        "description": "Ruby OpenSSL SHA-256 Digest"
    },
    {
        "id": "ruby.openssl.hmac.digest",
        "ecosystem": "ruby",
        "namespace": "OpenSSL::HMAC",
        "contract": "OpenSSL::HMAC",
        "symbol": "digest",
        "normalized_alg": "HMAC-SHA256",
        "primitive_type": "HASH",
        "key_size": 256,
        "classical_security_level": 256,
        "nist_quantum_security_level": 5,
        "default_risk": "LOW",
        "pqc_recommendation": "Maintain: HMAC provides keyed message authentication",
        "cwe": None,
        "description": "Ruby OpenSSL HMAC"
    },
    {
        "id": "ruby.openssl.pkey.rsa",
        "ecosystem": "ruby",
        "namespace": "OpenSSL::PKey::RSA",
        "contract": "OpenSSL::PKey",
        "symbol": "generate",
        "normalized_alg": "RSA-2048",
        "primitive_type": "SIGNATURE",
        "key_size": 2048,
        "classical_security_level": 112,
        "nist_quantum_security_level": 0,
        "default_risk": "HIGH",
        "pqc_recommendation": "Migrate: RSA vulnerable to Shor's algorithm; migrate to ML-DSA/ML-KEM",
        "cwe": "CWE-326",
        "description": "Ruby OpenSSL RSA Key Generation"
    },
    {
        "id": "ruby.openssl.pkey.ec",
        "ecosystem": "ruby",
        "namespace": "OpenSSL::PKey::EC",
        "contract": "OpenSSL::PKey",
        "symbol": "generate",
        "normalized_alg": "ECDSA-P256",
        "primitive_type": "SIGNATURE",
        "key_size": 256,
        "classical_security_level": 128,
        "nist_quantum_security_level": 0,
        "default_risk": "HIGH",
        "pqc_recommendation": "Migrate: EC vulnerable to Shor's algorithm; migrate to ML-DSA-65",
        "cwe": "CWE-326",
        "description": "Ruby OpenSSL EC Key Generation"
    },
    {
        "id": "ruby.openssl.kdf.pbkdf2",
        "ecosystem": "ruby",
        "namespace": "OpenSSL::KDF",
        "contract": "OpenSSL::KDF",
        "symbol": "pbkdf2_hmac",
        "normalized_alg": "PBKDF2",
        "primitive_type": "KEY_EXCHANGE",
        "key_size": 256,
        "classical_security_level": 128,
        "nist_quantum_security_level": 5,
        "default_risk": "MEDIUM",
        "pqc_recommendation": "Consider upgrade: Transition to Argon2id for password hashing",
        "cwe": None,
        "description": "Ruby OpenSSL PBKDF2 Key Derivation"
    },
    {
        "id": "ruby.openssl.kdf.hkdf",
        "ecosystem": "ruby",
        "namespace": "OpenSSL::KDF",
        "contract": "OpenSSL::KDF",
        "symbol": "hkdf",
        "normalized_alg": "HKDF",
        "primitive_type": "KEY_EXCHANGE",
        "key_size": 256,
        "classical_security_level": 256,
        "nist_quantum_security_level": 5,
        "default_risk": "LOW",
        "pqc_recommendation": "Maintain: HKDF is quantum-safe",
        "cwe": None,
        "description": "Ruby OpenSSL HKDF Key Derivation"
    },
    {
        "id": "ruby.activesupport.encryptor",
        "ecosystem": "ruby",
        "namespace": "ActiveSupport::MessageEncryptor",
        "contract": "HighLevelCrypto",
        "symbol": "new",
        "normalized_alg": "AES-256-GCM",
        "primitive_type": "ENCRYPTION",
        "key_size": 256,
        "classical_security_level": 256,
        "nist_quantum_security_level": 5,
        "default_risk": "LOW",
        "pqc_recommendation": "Maintain: ActiveSupport MessageEncryptor with AES-GCM",
        "cwe": None,
        "description": "Rails ActiveSupport MessageEncryptor"
    },

    # ---------------------------------------------------------
    # PYTHON ECOSYSTEM (cryptography.hazmat / hashlib)
    # ---------------------------------------------------------
    {
        "id": "python.hazmat.cipher.aes",
        "ecosystem": "python",
        "namespace": "cryptography.hazmat.primitives.ciphers.algorithms",
        "contract": "CipherAlgorithm",
        "symbol": "AES",
        "normalized_alg": "AES-256-GCM",
        "primitive_type": "ENCRYPTION",
        "key_size": 256,
        "classical_security_level": 256,
        "nist_quantum_security_level": 5,
        "default_risk": "LOW",
        "pqc_recommendation": "Maintain: AES-256 is quantum-safe under Grover's algorithm",
        "cwe": None,
        "description": "Python cryptography hazmat AES algorithm"
    },
    {
        "id": "python.hazmat.cipher.des",
        "ecosystem": "python",
        "namespace": "cryptography.hazmat.primitives.ciphers.algorithms",
        "contract": "CipherAlgorithm",
        "symbol": "TripleDES",
        "normalized_alg": "3DES",
        "primitive_type": "ENCRYPTION",
        "key_size": 192,
        "classical_security_level": 112,
        "nist_quantum_security_level": 0,
        "default_risk": "HIGH",
        "pqc_recommendation": "Migrate: 3DES is deprecated by NIST (Sweet32 vulnerability)",
        "cwe": "CWE-327",
        "description": "Python cryptography hazmat TripleDES"
    },
    {
        "id": "python.hashlib.md5",
        "ecosystem": "python",
        "namespace": "hashlib",
        "contract": "HashAlgorithm",
        "symbol": "md5",
        "normalized_alg": "MD5",
        "primitive_type": "HASH",
        "key_size": 128,
        "classical_security_level": 0,
        "nist_quantum_security_level": 0,
        "default_risk": "CRITICAL",
        "pqc_recommendation": "Migrate immediately: MD5 collisions broken; migrate to SHA-256",
        "cwe": "CWE-328",
        "description": "Python standard library hashlib.md5 (Broken)"
    },
    {
        "id": "python.hashlib.sha256",
        "ecosystem": "python",
        "namespace": "hashlib",
        "contract": "HashAlgorithm",
        "symbol": "sha256",
        "normalized_alg": "SHA-256",
        "primitive_type": "HASH",
        "key_size": 256,
        "classical_security_level": 256,
        "nist_quantum_security_level": 5,
        "default_risk": "LOW",
        "pqc_recommendation": "Maintain: SHA-256 is quantum-safe",
        "cwe": None,
        "description": "Python standard library hashlib.sha256"
    },
]

SEED_PACKAGE_RULES: List[Dict[str, Any]] = [
    # Post-Quantum Cryptography (PQC)
    {"ecosystem": "npm", "package_name": "@noble/post-quantum", "category": "POST_QUANTUM", "pqc_readiness": "MIGRATED_PQC", "description": "NIST FIPS 203/204/205 ML-KEM & ML-DSA", "recommendation": "Validated: Post-Quantum standard algorithm"},
    {"ecosystem": "cargo", "package_name": "pqcrypto", "category": "POST_QUANTUM", "pqc_readiness": "MIGRATED_PQC", "description": "Rust post-quantum cryptography bindings", "recommendation": "Validated: Post-Quantum standard algorithm"},
    {"ecosystem": "cargo", "package_name": "crystals-dilithium", "category": "POST_QUANTUM", "pqc_readiness": "MIGRATED_PQC", "description": "NIST ML-DSA reference implementation", "recommendation": "Validated: Post-Quantum standard algorithm"},
    {"ecosystem": "cargo", "package_name": "crystals-kyber", "category": "POST_QUANTUM", "pqc_readiness": "MIGRATED_PQC", "description": "NIST ML-KEM reference implementation", "recommendation": "Validated: Post-Quantum standard algorithm"},
    {"ecosystem": "pypi", "package_name": "oqs", "category": "POST_QUANTUM", "pqc_readiness": "MIGRATED_PQC", "description": "Open Quantum Safe Python wrapper", "recommendation": "Validated: Post-Quantum standard algorithm"},

    # Classical Asymmetric (Vulnerable to Shor's algorithm - HNDL Risk)
    {"ecosystem": "npm", "package_name": "node-forge", "category": "CLASSICAL_ASYMMETRIC", "pqc_readiness": "VULNERABLE_CLASSICAL", "description": "RSA/ECC classical cipher suite (HNDL risk)", "recommendation": "Urgent: Migrate classical RSA/ECC to hybrid NIST FIPS 203/204 (ML-KEM/ML-DSA)"},
    {"ecosystem": "npm", "package_name": "elliptic", "category": "CLASSICAL_ASYMMETRIC", "pqc_readiness": "VULNERABLE_CLASSICAL", "description": "Classical ECC curves (secp256k1, P-256)", "recommendation": "Urgent: Migrate classical RSA/ECC to hybrid NIST FIPS 203/204 (ML-KEM/ML-DSA)"},
    {"ecosystem": "npm", "package_name": "rsa", "category": "CLASSICAL_ASYMMETRIC", "pqc_readiness": "VULNERABLE_CLASSICAL", "description": "Classical RSA implementation", "recommendation": "Urgent: Migrate classical RSA/ECC to hybrid NIST FIPS 203/204 (ML-KEM/ML-DSA)"},
    {"ecosystem": "cargo", "package_name": "curve25519-dalek", "category": "CLASSICAL_ASYMMETRIC", "pqc_readiness": "VULNERABLE_CLASSICAL", "description": "X25519/Ed25519 curve operations (requires ML-KEM hybrid)", "recommendation": "Urgent: Migrate classical RSA/ECC to hybrid NIST FIPS 203/204 (ML-KEM/ML-DSA)"},
    {"ecosystem": "cargo", "package_name": "ed25519-dalek", "category": "CLASSICAL_ASYMMETRIC", "pqc_readiness": "VULNERABLE_CLASSICAL", "description": "Ed25519 signature scheme (requires ML-DSA hybrid)", "recommendation": "Urgent: Migrate classical RSA/ECC to hybrid NIST FIPS 203/204 (ML-KEM/ML-DSA)"},
    {"ecosystem": "pypi", "package_name": "cryptography", "category": "CLASSICAL_ASYMMETRIC", "pqc_readiness": "VULNERABLE_CLASSICAL", "description": "Python OpenSSL bindings (classical public key primitives)", "recommendation": "Urgent: Migrate classical RSA/ECC to hybrid NIST FIPS 203/204 (ML-KEM/ML-DSA)"},
    {"ecosystem": "pypi", "package_name": "pycryptodome", "category": "CLASSICAL_ASYMMETRIC", "pqc_readiness": "VULNERABLE_CLASSICAL", "description": "Python cryptography library (RSA, DSA, ECC)", "recommendation": "Urgent: Migrate classical RSA/ECC to hybrid NIST FIPS 203/204 (ML-KEM/ML-DSA)"},
    {"ecosystem": "pypi", "package_name": "pyopenssl", "category": "CLASSICAL_ASYMMETRIC", "pqc_readiness": "VULNERABLE_CLASSICAL", "description": "Python OpenSSL wrapper", "recommendation": "Urgent: Migrate classical RSA/ECC to hybrid NIST FIPS 203/204 (ML-KEM/ML-DSA)"},
    {"ecosystem": "pypi", "package_name": "paramiko", "category": "CLASSICAL_ASYMMETRIC", "pqc_readiness": "VULNERABLE_CLASSICAL", "description": "SSH client/server with classical RSA/ECDSA handshakes", "recommendation": "Urgent: Migrate classical RSA/ECC to hybrid NIST FIPS 203/204 (ML-KEM/ML-DSA)"},

    # Blockchain / Enterprise Frameworks
    {"ecosystem": "go", "package_name": "github.com/hyperledger/fabric-contract-api-go", "category": "BLOCKCHAIN_CORE", "pqc_readiness": "CLASSICAL_HYBRID", "description": "Hyperledger Fabric chaincode SDK (PDC & state operations)", "recommendation": "Evaluate PQC chaincode and ledger support for post-quantum transaction signing"},
    {"ecosystem": "go", "package_name": "github.com/hyperledger/fabric-gateway", "category": "BLOCKCHAIN_CORE", "pqc_readiness": "CLASSICAL_HYBRID", "description": "Fabric client gateway with gRPC TLS", "recommendation": "Evaluate PQC chaincode and ledger support for post-quantum transaction signing"},
    {"ecosystem": "npm", "package_name": "ethers", "category": "BLOCKCHAIN_CORE", "pqc_readiness": "VULNERABLE_CLASSICAL", "description": "Ethereum Web3 client with secp256k1 ECDSA", "recommendation": "Urgent: Migrate classical blockchain signing keys to post-quantum hybrid"},
    {"ecosystem": "npm", "package_name": "web3", "category": "BLOCKCHAIN_CORE", "pqc_readiness": "VULNERABLE_CLASSICAL", "description": "Ethereum Web3 RPC framework", "recommendation": "Urgent: Migrate classical blockchain signing keys to post-quantum hybrid"},

    # Symmetric / Hash / KDFs
    {"ecosystem": "npm", "package_name": "crypto-js", "category": "SYMMETRIC_OR_HASH", "pqc_readiness": "SAFE_SYMMETRIC", "description": "AES, SHA-2/3, HMAC symmetric algorithms", "recommendation": "Maintain: Symmetric/hash algorithm (ensure key size >= 256 bits for Grover resistance)"},
    {"ecosystem": "cargo", "package_name": "sha2", "category": "SYMMETRIC_OR_HASH", "pqc_readiness": "SAFE_SYMMETRIC", "description": "SHA-256 / SHA-512 cryptographic hash functions", "recommendation": "Maintain: Symmetric/hash algorithm (ensure key size >= 256 bits for Grover resistance)"},
    {"ecosystem": "cargo", "package_name": "aes", "category": "SYMMETRIC_OR_HASH", "pqc_readiness": "SAFE_SYMMETRIC", "description": "AES symmetric block cipher (AES-256 quantum-safe)", "recommendation": "Maintain: Symmetric/hash algorithm (ensure key size >= 256 bits for Grover resistance)"},
    {"ecosystem": "npm", "package_name": "jsonwebtoken", "category": "SYMMETRIC_OR_HASH", "pqc_readiness": "DEPENDS_ON_ALG", "description": "JWT auth (HMAC-SHA256 safe; RS256 vulnerable)", "recommendation": "Audit primitive usage: ensure parameters meet post-quantum and Grover security thresholds"},
    {"ecosystem": "npm", "package_name": "bcrypt", "category": "SYMMETRIC_OR_HASH", "pqc_readiness": "SAFE_SYMMETRIC", "description": "Password hashing function", "recommendation": "Maintain: Symmetric/hash algorithm (ensure key size >= 256 bits for Grover resistance)"},
    {"ecosystem": "npm", "package_name": "argon2", "category": "SYMMETRIC_OR_HASH", "pqc_readiness": "SAFE_SYMMETRIC", "description": "Memory-hard password hashing", "recommendation": "Maintain: Symmetric/hash algorithm (ensure key size >= 256 bits for Grover resistance)"},
    {"ecosystem": "go", "package_name": "golang.org/x/crypto", "category": "SYMMETRIC_OR_HASH", "pqc_readiness": "DEPENDS_ON_ALG", "description": "Go extended cryptographic algorithms (Argon2, Bcrypt, ChaCha20Poly1305, SSH)", "recommendation": "Audit primitive usage: ensure parameters meet post-quantum and Grover security thresholds"},
]

def seed_database(conn: sqlite3.Connection) -> None:
    """Inserts seed signatures and package rules into the SQLite database."""
    cursor = conn.cursor()

    for sig in SEED_SIGNATURES:
        cursor.execute("""
            INSERT OR REPLACE INTO crypto_signatures (
                id, ecosystem, namespace, contract, symbol, normalized_alg,
                primitive_type, key_size, classical_security_level, nist_quantum_security_level,
                default_risk, pqc_recommendation, cwe, description
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            sig["id"], sig["ecosystem"], sig["namespace"], sig["contract"], sig["symbol"],
            sig["normalized_alg"], sig["primitive_type"], sig.get("key_size"),
            sig.get("classical_security_level"), sig.get("nist_quantum_security_level"),
            sig["default_risk"], sig["pqc_recommendation"], sig.get("cwe"), sig.get("description")
        ))

    for pkg in SEED_PACKAGE_RULES:
        cursor.execute("""
            INSERT OR REPLACE INTO package_manifest_rules (
                ecosystem, package_name, category, pqc_readiness, description, recommendation
            ) VALUES (?, ?, ?, ?, ?, ?)
        """, (
            pkg["ecosystem"], pkg["package_name"], pkg["category"],
            pkg["pqc_readiness"], pkg["description"], pkg["recommendation"]
        ))

    cursor.execute("INSERT OR REPLACE INTO db_metadata (key, value) VALUES ('version', '2026.1')")
    cursor.execute("INSERT OR REPLACE INTO db_metadata (key, value) VALUES ('seeded_at', datetime('now'))")
    conn.commit()
